[package]
name = "example-source"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
komorei = { path = "../../crates/lib" }

[dev-dependencies]
komorei = { path = "../../crates/lib", features = ["test"] }
komorei-test = { path = "../../crates/test-macro" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "s"
strip = true
lto = true
