[book]
title = "Komorei Source Development"
authors = ["Skitty (upstream aidoku-rs)"]
language = "en"
description = "This book outlines how to get started with Komorei source development using the komorei-sdk."

[output.html]
git-repository-url = "https://github.com/tachibana-shin/komorei-sdk"
sidebar-header-nav = false